{{ if .Values.frontendReplicasMax }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Release.Name}}-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Release.Name}}-frontend
  minReplicas: {{ .Values.frontendReplicas }}
  maxReplicas: {{ .Values.frontendReplicasMax }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 90
          type: Utilization
{{ end }}